# docker-compose.yml for a Solr and ZooKeeper node cluster.

version: '3.7'
services:
  nptn-solr-01:
    container_name: nptn_solr_01
    image: solr:latest
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=nptn-zoo-01:2181
      - ZK_CLIENT_TIMEOUT=120000
      - SOLR_HEAP=2g
    ports:
     - 8983:8983
    networks:
      - solr
    depends_on:
      - nptn-zoo-01

  nptn-zoo-01:
    image: zookeeper:latest
    container_name: nptn_zoo_01
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: conf,cons,crst,dump,envi,ruok,srst,srvr,stat,wchs,wchc,wchp,mntr
    networks:
      - solr

networks:
  solr:
    ipam:
      driver: default
      config:
        - subnet: "172.26.0.0/28"
